# -----------------------------------------------------------------------
# Configuration file for https://travis-ci.org/elastic/elasticsearch-ruby
# -----------------------------------------------------------------------

sudo: false

language: ruby

cache: bundler

branches:
  only:
    - master
    - travis

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6

jdk:
  - oraclejdk8

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

matrix:
  exclude:
    - rvm: 2.3.3
      jdk: oraclejdk8
      env: TEST_SUITE=integration
    - rvm: 2.2.6
      jdk: oraclejdk8
      env: TEST_SUITE=integration

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.14.2
  - curl -sS https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.tar.gz | tar xz -C /tmp
  - echo "RUN ES"
  - /tmp/elasticsearch-5.1.2/bin/elasticsearch --daemonize -E path.data=/tmp
  - rake setup
  - rake elasticsearch:update

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - SERVER=start TEST_CLUSTER_LOGS=/tmp/log TEST_BUILD_REF=tags/v5.1.2 TEST_CLUSTER_COMMAND=/tmp/elasticsearch-5.1.2/bin/elasticsearch rake test:$TEST_SUITE

notifications:
  disable: true
